name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  APP_KEY: base64:uz4B1RtFO57QGzbZX1kRYX9hIRB50+QzqFeg9zbFJlY=

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Remove local dev repositories
        run: composer config --unset repositories
  
      - name: generate keys
        run: |
          openssl genrsa -out storage/oauth-private.key 4096
          openssl rsa -in storage/oauth-private.key -pubout -out storage/oauth-public.key
  
      - name: fix key permissions
        run: chmod -R 600 storage/*.key

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: list install dependencies
        run: composer show -D
      
      - name: install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: vendor/bin/pest
        env:
          PLATFORM_DB_CONNECTION: testing_platform
